sftp:
  user: your_user_name
  host: sftp.nyse.com
  port: 22
  key_file: path_to_private_key
  max_retry: 3 # self-defined variable. maximum retry times connect to sftp server
download:
  create_dir: True  # True: create dir recursively | False: do not create
  safe_to:
    EQY_US_ALL_ADMIN: L:\2024\EQY_US_ALL_ADMIN
    EQY_US_ALL_BBO_ADMIN: L:\2024\EQY_US_ALL_BBO_ADMIN
    EQY_US_ALL_NBBO: L:\2024\EQY_US_ALL_NBBO
    EQY_US_ALL_REF_MASTER: L:\2024\EQY_US_ALL_REF_MASTER
    EQY_US_ALL_REF_MASTER_PD: L:\2024\EQY_US_ALL_REF_MASTER_PD
    EQY_US_ALL_TRADE: L:\2024\EQY_US_ALL_TRADE
    EQY_US_ALL_TRADE_ADMIN: L:\2024\EQY_US_ALL_TRADE_ADMIN
    SPLITS_US_ALL_BBO: E:\SPLITS_US_ALL_BBO
  only: # only download following types of files
    - SPLITS_US_ALL_BBO
    - EQY_US_ALL_ADMIN 
    - EQY_US_ALL_BBO_ADMIN
    - EQY_US_ALL_NBBO
    - EQY_US_ALL_REF_MASTER
    - EQY_US_ALL_TRADE
    - EQY_US_ALL_TRADE_ADMIN
  start_year: 2024
  start_month: 7
  end_year: 2024
  end_month: 7
sas: 
  start_year: 2024
  start_month: 5
  start_day: 20
  end_year: 2024
  end_month: 5
  end_day: 20
  task:  
    bbo:
      program: C:\temp\bbo_test.sas
      source: # not used
        - SPLITS_US_ALL_BBO
      result:
        7z: M:\2024cq
    except_bbo:
      program: C:\temp\except_bbo_test.sas
      source: # not used
        - EQY_US_ALL_REF_MASTER
        - EQY_US_ALL_BBO_ADMIN
        - EQY_US_ALL_TRADE_ADMIN # include EQY_US_ALL_ADMIN_CTS, EQY_US_ALL_ADMIN_UTP
        - EQY_US_ALL_ADMIN
        - EQY_US_ALL_TRADE
        - EQY_US_ALL_NBBO
      result:
        7z: k:\master2024