sftp:
  user: username
  host: sftp.nyse.com
  port: 22
  key_file: pathto/keyfile
  max_retry: 3 # self-defined variable
redis:
  host: localhost
  port: 6379
  db: 0
mysql:
  host: localhost
  user: root
  password: root_password
  database: 
    prod: nyse 
    test: nyse_test
  auth_plugin: mysql_native_password
alert: # not used
  from_addr: email_address
  to_addr: 
    - email_address
  password: app_password
download:
  create_dir: True  # True: create dir recursively | False: do not create
  safe_to:
    EQY_US_ALL_ADMIN: L:\2024\EQY_US_ALL_ADMIN
    EQY_US_ALL_BBO_ADMIN: L:\2024\EQY_US_ALL_BBO_ADMIN
    EQY_US_ALL_NBBO: L:\2024\EQY_US_ALL_NBBO
    EQY_US_ALL_REF_MASTER: L:\2024\EQY_US_ALL_REF_MASTER
    EQY_US_ALL_REF_MASTER_PD: L:\2024\EQY_US_ALL_REF_MASTER_PD
    EQY_US_ALL_TRADE: L:\2024\EQY_US_ALL_TRADE
    EQY_US_ALL_TRADE_ADMIN: L:\2024\EQY_US_ALL_TRADE_ADMIN
    SPLITS_US_ALL_BBO: E:\SPLITS_US_ALL_BBO
  only:
    - SPLITS_US_ALL_BBO
    - EQY_US_ALL_ADMIN 
    - EQY_US_ALL_BBO_ADMIN
    - EQY_US_ALL_NBBO
    - EQY_US_ALL_REF_MASTER
    - EQY_US_ALL_TRADE
    - EQY_US_ALL_TRADE_ADMIN
  ignore: # not implemented yet
    - EQY_US_ALL_BBO   # This type of data is not used 
    - EQY_US_ALL_REF_MASTER_PD # This type of data is not used 
sas: 
  task:
    bbo:
      program: C:\temp\bbo_test.sas
      source:
        - SPLITS_US_ALL_BBO
      result:
        sas_data: C:\temp
        7z: M:\2024cq
    except_bbo:
      program: C:\temp\except_bbo_test.sas
      source: 
        - EQY_US_ALL_REF_MASTER
        - EQY_US_ALL_BBO_ADMIN
        - EQY_US_ALL_TRADE_ADMIN
        - EQY_US_ALL_ADMIN
        - EQY_US_ALL_TRADE
        - EQY_US_ALL_NBBO
      result:
        7z: k:\master2024
  